package Interfaz;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class DetalleProducto extends JDialog {
    private JLabel txtNombre;
    private JLabel txtPrecio;
    private JButton agregarAlCarritoButton;
    private JPanel panelDetalles;
    private JPanel panelizquierdo;
    private JPanel panelDerecho;
    private JButton regresarButton;
    private JLabel txtStock;
    private JLabel txtMarca;
    private JTextArea descripciónTextArea;
    private JLabel icon;
    private JLabel txtSKU;
    private JButton marcaButton;
    private JButton stockButton;
    private JButton descripcionButton;
    private JButton skuButton;

    public DetalleProducto() {
        setContentPane(panelDetalles);
        setModal(true);
        getRootPane().setDefaultButton(regresarButton);
        Estilos.hacerBotonRedondo(agregarAlCarritoButton);
        Estilos.hacerBotonRedondo(regresarButton);
        Estilos.hacerBotonRedondo(marcaButton);
        Estilos.hacerBotonRedondo(stockButton);
        Estilos.hacerBotonRedondo(descripcionButton);
        Estilos.hacerBotonRedondo(skuButton);

        regresarButton.addActionListener(e -> dispose());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);


    }

    public void setDatos(String SKU, String nombre, String marca, String precio, String stock, String descripcion, Icon rutaImagen) {
        txtNombre.setText(nombre);
        txtSKU.setText(SKU);
        txtMarca.setText(marca);
        txtPrecio.setText(precio);
        txtStock.setText(stock + " unidades");
        descripciónTextArea.setText(descripcion);
        icon.setIcon(rutaImagen);

        // lblImagen.setIcon(new ImageIcon(rutaImagen));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelDetalles = new JPanel();
        panelDetalles.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelDetalles.setBackground(new Color(-1));
        panelDetalles.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-13408851)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JSplitPane splitPane1 = new JSplitPane();
        panelDetalles.add(splitPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        panelizquierdo = new JPanel();
        panelizquierdo.setLayout(new GridLayoutManager(1, 1, new Insets(20, 20, 20, 20), -1, -1));
        panelizquierdo.setBackground(new Color(-1));
        splitPane1.setLeftComponent(panelizquierdo);
        panelizquierdo.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        icon = new JLabel();
        icon.setIcon(new ImageIcon(getClass().getResource("/Interfaz/Celular.png")));
        icon.setText("");
        panelizquierdo.add(icon, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelDerecho = new JPanel();
        panelDerecho.setLayout(new GridLayoutManager(8, 2, new Insets(20, 20, 20, 20), -1, -1));
        panelDerecho.setBackground(new Color(-1));
        splitPane1.setRightComponent(panelDerecho);
        panelDerecho.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        txtNombre = new JLabel();
        Font txtNombreFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 36, txtNombre.getFont());
        if (txtNombreFont != null) txtNombre.setFont(txtNombreFont);
        txtNombre.setText("Nombre");
        panelDerecho.add(txtNombre, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPrecio = new JLabel();
        Font txtPrecioFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 28, txtPrecio.getFont());
        if (txtPrecioFont != null) txtPrecio.setFont(txtPrecioFont);
        txtPrecio.setForeground(new Color(-13408851));
        txtPrecio.setText("Precio");
        panelDerecho.add(txtPrecio, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtMarca = new JLabel();
        Font txtMarcaFont = this.$$$getFont$$$("Segoe UI", Font.PLAIN, 18, txtMarca.getFont());
        if (txtMarcaFont != null) txtMarca.setFont(txtMarcaFont);
        txtMarca.setText("Marca");
        panelDerecho.add(txtMarca, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtStock = new JLabel();
        Font txtStockFont = this.$$$getFont$$$("Segoe UI", Font.PLAIN, 18, txtStock.getFont());
        if (txtStockFont != null) txtStock.setFont(txtStockFont);
        txtStock.setText("Stock");
        panelDerecho.add(txtStock, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtSKU = new JLabel();
        Font txtSKUFont = this.$$$getFont$$$("Segoe UI", Font.PLAIN, 18, txtSKU.getFont());
        if (txtSKUFont != null) txtSKU.setFont(txtSKUFont);
        txtSKU.setText("SKU");
        panelDerecho.add(txtSKU, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        agregarAlCarritoButton = new JButton();
        agregarAlCarritoButton.setText("Agregar al carrito");
        panelDerecho.add(agregarAlCarritoButton, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        regresarButton = new JButton();
        regresarButton.setText("Regresar");
        panelDerecho.add(regresarButton, new GridConstraints(7, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        marcaButton = new JButton();
        marcaButton.setText("marca");
        panelDerecho.add(marcaButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stockButton = new JButton();
        stockButton.setText("stock");
        panelDerecho.add(stockButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descripcionButton = new JButton();
        descripcionButton.setText("descripcion");
        panelDerecho.add(descripcionButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        skuButton = new JButton();
        skuButton.setText("sku");
        panelDerecho.add(skuButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descripciónTextArea = new JTextArea();
        descripciónTextArea.setBackground(new Color(-1));
        Font descripciónTextAreaFont = this.$$$getFont$$$("Segoe UI", Font.PLAIN, 18, descripciónTextArea.getFont());
        if (descripciónTextAreaFont != null) descripciónTextArea.setFont(descripciónTextAreaFont);
        descripciónTextArea.setLineWrap(true);
        descripciónTextArea.setRows(4);
        descripciónTextArea.setText("Descripción");
        descripciónTextArea.setWrapStyleWord(true);
        panelDerecho.add(descripciónTextArea, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 30), new Dimension(300, 80), 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelDetalles;
    }

}
