package Interfaz;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class TarjetaProducto extends JFrame {
    private JPanel panelTarjeta;
    private JLabel iconCelular;
    private JButton verDetallesButton;
    private JLabel txtPrecio;
    private JLabel txtNombre;
    private String skuGuardado;
    private String descripcionGuardada;
    private String stockGuardado;
    private String marcaGuardada;

    // CONSTRUCTOR: Aquí recibimos los datos únicos de cada producto
    public TarjetaProducto(String sku, String nombre, String marca, String precio, String stock, String descripcion, Icon imagen) {

        // Asignar el texto que se va a mostrar
        $$$setupUI$$$();
        txtNombre.setText(nombre);
        txtPrecio.setText(precio);
        iconCelular.setIcon(imagen);

        this.skuGuardado = sku;
        this.descripcionGuardada = descripcion;
        this.stockGuardado = stock;
        this.marcaGuardada = marca;

        // Asignar la imagen
        Estilos.hacerBotonRedondo(verDetallesButton);
        // Acción del botón
        verDetallesButton.addActionListener(e -> {
            mostrarDetalleProducto();
        });

    }

    private void mostrarDetalleProducto() {
        DetalleProducto miniVentana = new DetalleProducto();
        miniVentana.pack();
        miniVentana.setDatos(this.skuGuardado, txtNombre.getText(), this.marcaGuardada, txtPrecio.getText(),
                this.stockGuardado, this.descripcionGuardada, iconCelular.getIcon());
        miniVentana.setSize(1000, 600);
        miniVentana.setLocationRelativeTo(null); // Centrar
        miniVentana.setVisible(true);
    }

    // Método necesario para que la Ventana1 pueda "agarrar" este panel y mostrarlo
    public JPanel getPanel() {
        return panelTarjeta;
    }

    private void createUIComponents() {
        panelTarjeta = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                // Configuramos los gráficos
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Pintamos el fondo blanco con bordes redondeados
                g2.setColor(Color.WHITE);
                // (x, y, ancho, alto, radioX, radioY) -> Radio 30 para esquinas redondas
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

                // 3. Pintamos un borde GRIS suave alrededor
                g2.setColor(new Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                g2.dispose();
            }
        };

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panelTarjeta.setLayout(new GridLayoutManager(4, 1, new Insets(10, 10, 10, 10), -1, -1));
        panelTarjeta.setPreferredSize(new Dimension(200, 300));
        txtNombre = new JLabel();
        Font txtNombreFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 15, txtNombre.getFont());
        if (txtNombreFont != null) txtNombre.setFont(txtNombreFont);
        txtNombre.setText("Nombre");
        panelTarjeta.add(txtNombre, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPrecio = new JLabel();
        Font txtPrecioFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 15, txtPrecio.getFont());
        if (txtPrecioFont != null) txtPrecio.setFont(txtPrecioFont);
        txtPrecio.setText("Precio");
        panelTarjeta.add(txtPrecio, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        verDetallesButton = new JButton();
        Font verDetallesButtonFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 15, verDetallesButton.getFont());
        if (verDetallesButtonFont != null) verDetallesButton.setFont(verDetallesButtonFont);
        verDetallesButton.setText("Ver detalles");
        panelTarjeta.add(verDetallesButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        iconCelular = new JLabel();
        iconCelular.setFocusCycleRoot(false);
        iconCelular.setIcon(new ImageIcon(getClass().getResource("/Interfaz/Celular.png")));
        iconCelular.setText("");
        panelTarjeta.add(iconCelular, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelTarjeta;
    }

}