package Interfaz;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.GridLayout;
import java.util.Locale;

// La clase extiende JFrame Ventana1 ES la ventana.
public class Ventana1 extends JFrame {

    // Componentes del .form
    private JPanel panelVentana1;
    private JPanel panelHeader;
    private JPanel panelContent;
    private JLabel txtTienda;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;
    private JButton button7;

    public Ventana1() {
        super("Mi Aplicación");
        //Configuraciones de la ventana
        configurarVentana();
        //Agupacion de los ajustes para que no haya tanta cosa en el constructor
        estilosBotones();
//Aca se arregla la estructura del panel, se coloca el header arriba, se agrega es scroll y se dividen en cuadritos para poner las tarjetas
        armarEstucturaPanel();
        //Aca se van llenando los datos en las tarjetas
        VisualizacionProductos.cargarProductos(panelContent);

        // Refrescar
        panelVentana1.revalidate();
        panelVentana1.repaint();
    }

    private void configurarVentana() {
        this.setContentPane(panelVentana1);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(1910, 1790);
        this.setLocationRelativeTo(null);
    }

    private void armarEstucturaPanel() {
        // Para dejar de usar el diseño de IntelliJ y usa BorderLayout
        //Le ordena al panelVentana1 que se comporte usando el esquema Norte, Sur, Este, Oeste y Centro
        panelVentana1.setLayout(new BorderLayout());
        //Toma el panelHeader y lo pega en el Norte (arriba) de la ventana.
        panelVentana1.add(panelHeader, BorderLayout.NORTH);
        // Sacamos el panelContent original del flujo antiguo
        panelVentana1.remove(panelContent);

        // Creamos el Scroll y metemos el contenido
        JScrollPane scroll = new JScrollPane(panelContent);
        scroll.getVerticalScrollBar().setUnitIncrement(15); //Para que el scroll vaya más rápido
        scroll.setBorder(null); //Quita el borde gris de 1 píxel que trae el scroll por defecto

        // Pegamos el Scroll al CENTRO
        panelVentana1.add(scroll, BorderLayout.CENTER);
        panelContent.setBorder(BorderFactory.createEmptyBorder(20, 40, 20, 40));
        panelContent.setLayout(new GridLayout(0, 5, 15, 15));
        panelContent.setBackground(Color.WHITE);

    }


    private void estilosBotones() {
        // Interfaz.Estilos
        Estilos.botonesBonitos(button1);
        Estilos.botonesBonitos(button2);
        Estilos.botonesBonitos(button3);
        Estilos.botonesBonitos(button4);
        Estilos.botonesBonitos(button5);
        Estilos.botonesBonitos2(button6);
        Estilos.botonesBonitos2(button7);
    }

    //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>MAIN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    public static void main(String[] args) {
        try {
            // Esto hace que el programa use el diseño del sistema operativo Windows
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //Asegura que la ventana se dibuje en el hilo correcto de memoria para evitar errores
        SwingUtilities.invokeLater(() -> {
            Ventana1 frame = new Ventana1();
            frame.setVisible(true);
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelVentana1 = new JPanel();
        panelVentana1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, 0));
        panelVentana1.setAutoscrolls(false);
        panelVentana1.setBackground(new Color(-14605013));
        panelVentana1.putClientProperty("html.disable", Boolean.FALSE);
        panelHeader = new JPanel();
        panelHeader.setLayout(new GridLayoutManager(2, 6, new Insets(0, 0, 0, 0), 0, -1));
        panelHeader.setBackground(new Color(-1118743));
        panelVentana1.add(panelHeader, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        button1 = new JButton();
        Font button1Font = this.$$$getFont$$$("Consolas", Font.BOLD, -1, button1.getFont());
        if (button1Font != null) button1.setFont(button1Font);
        button1.setText("Celulares");
        panelHeader.add(button1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button2 = new JButton();
        Font button2Font = this.$$$getFont$$$("Consolas", Font.BOLD, -1, button2.getFont());
        if (button2Font != null) button2.setFont(button2Font);
        button2.setText("Periféricos");
        panelHeader.add(button2, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button3 = new JButton();
        Font button3Font = this.$$$getFont$$$("Consolas", Font.BOLD, -1, button3.getFont());
        if (button3Font != null) button3.setFont(button3Font);
        button3.setText("Computadoras");
        panelHeader.add(button3, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button4 = new JButton();
        Font button4Font = this.$$$getFont$$$("Consolas", Font.BOLD, -1, button4.getFont());
        if (button4Font != null) button4.setFont(button4Font);
        button4.setText("Tablets");
        panelHeader.add(button4, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button5 = new JButton();
        Font button5Font = this.$$$getFont$$$("Consolas", Font.BOLD, -1, button5.getFont());
        if (button5Font != null) button5.setFont(button5Font);
        button5.setText("Componentes");
        panelHeader.add(button5, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setIcon(new ImageIcon(getClass().getResource("/Interfaz/Logo1.png")));
        label1.setText("");
        panelHeader.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTienda = new JLabel();
        Font txtTiendaFont = this.$$$getFont$$$("Consolas", Font.BOLD, 22, txtTienda.getFont());
        if (txtTiendaFont != null) txtTienda.setFont(txtTiendaFont);
        txtTienda.setText("Tech System Core");
        panelHeader.add(txtTienda, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button6 = new JButton();
        button6.setBackground(new Color(-1118743));
        button6.setText("Iniciar Sesion");
        panelHeader.add(button6, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        button7 = new JButton();
        button7.setBackground(new Color(-1118743));
        button7.setText("Registrarse");
        panelHeader.add(button7, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelContent = new JPanel();
        panelContent.setLayout(new GridBagLayout());
        panelVentana1.add(panelContent, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelVentana1;
    }

}